# Generated by Django 4.1.3 on 2023-04-16 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_fname', models.CharField(max_length=50)),
                ('customer_lname', models.CharField(max_length=50)),
                ('customer_username', models.CharField(max_length=50)),
                ('customer_email', models.EmailField(max_length=25)),
                ('customer_password', models.CharField(max_length=125)),
                ('customer_login_history', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
