# Generated by Django 4.2.1 on 2023-05-19 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=100)),
                ('class_instructor', models.CharField(max_length=100)),
                ('class_startDay', models.CharField(choices=[('Sun', 'Sunday'), ('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Everyday', 'Everyday'), ('NONE', 'NONE')], default='Sun', max_length=8)),
                ('class_endDay', models.CharField(choices=[('Sun', 'Sunday'), ('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Everyday', 'Everyday'), ('NONE', 'NONE')], default='Sun', max_length=8)),
                ('class_time', models.TimeField()),
                ('class_image', models.ImageField(upload_to='static/image/classes/')),
                ('class_info', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cquery_name', models.CharField(max_length=100)),
                ('Cquery_email', models.EmailField(max_length=100)),
                ('Cquery_class', models.CharField(max_length=100)),
                ('Cquery_comment', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_fname', models.CharField(max_length=100)),
                ('customer_lname', models.CharField(max_length=100)),
                ('customer_username', models.CharField(max_length=100)),
                ('customer_email', models.EmailField(max_length=100)),
                ('customer_password', models.CharField(max_length=250)),
                ('customer_login_history', models.DateTimeField()),
                ('customer_resetcode', models.IntegerField(blank=True, null=True)),
                ('customer_age', models.IntegerField(blank=True, null=True)),
                ('customer_gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=6)),
                ('customer_phone', models.IntegerField(blank=True, null=True)),
                ('customer_address', models.CharField(blank=True, max_length=500)),
                ('customer_height', models.IntegerField(blank=True, null=True)),
                ('customer_weight', models.IntegerField(blank=True, null=True)),
                ('customer_bmi', models.IntegerField(blank=True, null=True)),
                ('joined_class', models.ManyToManyField(blank=True, null=True, to='GYMBookerapp.class')),
            ],
        ),
    ]
