# Generated by Django 4.1.7 on 2023-05-26 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=100)),
                ('class_instructor', models.CharField(max_length=100)),
                ('class_time', models.TimeField()),
                ('class_image', models.ImageField(upload_to='static/image/classes/')),
                ('class_info', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cquery_name', models.CharField(max_length=100)),
                ('Cquery_email', models.EmailField(max_length=100)),
                ('Cquery_class', models.CharField(max_length=100)),
                ('Cquery_comment', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Days',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(blank=True, max_length=9, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_name', models.CharField(max_length=100)),
                ('membership_price', models.IntegerField()),
                ('membership_image', models.ImageField(upload_to='static/image/membership/')),
                ('membership_fac1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='membership_fac1_set', to='GYMBookerapp.facility')),
                ('membership_fac2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='membership_fac2_set', to='GYMBookerapp.facility')),
                ('membership_fac3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='membership_fac3_set', to='GYMBookerapp.facility')),
                ('membership_fac4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='membership_fac4_set', to='GYMBookerapp.facility')),
                ('membership_fac5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='membership_fac5_set', to='GYMBookerapp.facility')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_fname', models.CharField(max_length=100)),
                ('customer_lname', models.CharField(max_length=100)),
                ('customer_username', models.CharField(max_length=100)),
                ('customer_email', models.EmailField(max_length=100)),
                ('customer_password', models.CharField(max_length=250)),
                ('customer_login_history', models.DateTimeField(blank=True, null=True)),
                ('customer_resetcode', models.IntegerField(blank=True, null=True)),
                ('customer_age', models.IntegerField(blank=True, null=True)),
                ('customer_gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=6)),
                ('customer_phone', models.BigIntegerField(blank=True, null=True)),
                ('customer_address', models.CharField(blank=True, max_length=500)),
                ('customer_height', models.IntegerField(blank=True, null=True)),
                ('customer_weight', models.IntegerField(blank=True, null=True)),
                ('customer_bmi', models.IntegerField(blank=True, null=True)),
                ('customer_membership_joinedDate', models.DateField(blank=True, null=True)),
                ('customer_membership_exipredDate', models.DateField(blank=True, null=True)),
                ('customer_membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GYMBookerapp.membership')),
                ('joined_class', models.ManyToManyField(blank=True, to='GYMBookerapp.class')),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='class_day',
            field=models.ManyToManyField(blank=True, to='GYMBookerapp.days'),
        ),
    ]
