# Generated by Django 4.2.1 on 2023-05-19 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GYMBookerapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_phone',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='joined_class',
            field=models.ManyToManyField(blank=True, to='GYMBookerapp.class'),
        ),
    ]
