# Generated by Django 4.2.1 on 2023-05-31 09:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('GYMBookerapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='static/image/customer_image/'),
            preserve_default=False,
        ),
    ]
