# Generated by Django 4.2.1 on 2023-05-14 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GYMBookerapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='class_day',
        ),
        migrations.AddField(
            model_name='class',
            name='class_endDay',
            field=models.CharField(choices=[('Sun', 'Sunday'), ('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Everyday', 'Everyday')], default='Sun', max_length=8),
        ),
        migrations.AddField(
            model_name='class',
            name='class_startDay',
            field=models.CharField(choices=[('Sun', 'Sunday'), ('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Everyday', 'Everyday')], default='Sun', max_length=8),
        ),
    ]
