# Generated by Django 4.2.1 on 2023-07-12 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GYMBookerapp', '0002_customer_customer_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_dob',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/image/customer_image/'),
        ),
    ]
