# Generated by Django 4.2.1 on 2023-05-14 03:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('GYMBookerapp', '0002_remove_class_class_day_class_class_endday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_resetcode',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
