# Generated by Django 4.2.1 on 2023-05-05 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GYMBookerapp', '0003_sendmail'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cquery_name', models.CharField(max_length=100)),
                ('Cquery_email', models.EmailField(max_length=100)),
                ('Cquery_class', models.CharField(max_length=100)),
                ('Cquery_comment', models.CharField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='SendMail',
        ),
    ]
