# Generated by Django 4.2.1 on 2023-07-12 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GYMBookerapp', '0003_customer_customer_dob_alter_customer_customer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
