# Generated by Django 4.2.1 on 2023-05-23 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GYMBookerapp', '0003_facility_alter_class_class_endday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='membership_fac2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='membership_fac2_set', to='GYMBookerapp.facility'),
        ),
        migrations.AddField(
            model_name='membership',
            name='membership_fac3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='membership_fac3_set', to='GYMBookerapp.facility'),
        ),
        migrations.AddField(
            model_name='membership',
            name='membership_fac4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='membership_fac4_set', to='GYMBookerapp.facility'),
        ),
        migrations.AddField(
            model_name='membership',
            name='membership_fac5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='membership_fac5_set', to='GYMBookerapp.facility'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='membership_fac1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='membership_fac1_set', to='GYMBookerapp.facility'),
        ),
    ]
