# Generated by Django 4.2.1 on 2023-05-23 12:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('GYMBookerapp', '0004_membership_membership_fac2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='membership_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='static/image/membershipimg/'),
            preserve_default=False,
        ),
    ]
