# Generated by Django 4.2.1 on 2023-05-14 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GYMBookerapp', '0004_alter_customer_customer_resetcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='class_endDay',
            field=models.CharField(choices=[('Sun', 'Sunday'), ('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Everyday', 'Everyday'), ('NONE', 'NONE')], default='Sun', max_length=8),
        ),
        migrations.AlterField(
            model_name='class',
            name='class_startDay',
            field=models.CharField(choices=[('Sun', 'Sunday'), ('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Everyday', 'Everyday'), ('NONE', 'NONE')], default='Sun', max_length=8),
        ),
    ]
