# Generated by Django 4.2.1 on 2023-05-23 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GYMBookerapp', '0005_membership_membership_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='membership_image',
            field=models.ImageField(upload_to='static/image/membership/'),
        ),
    ]
