# Generated by Django 4.2.1 on 2023-10-02 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GYMBookerapp', '0005_customer_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
