# Generated by Django 4.2.1 on 2023-05-19 01:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('GYMBookerapp', '0005_alter_class_class_endday_alter_class_class_startday'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='class_info',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
    ]
