# Generated by Django 4.2.1 on 2023-05-19 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GYMBookerapp', '0006_class_class_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='customer',
            field=models.ManyToManyField(to='GYMBookerapp.customer'),
        ),
    ]
