# Generated by Django 4.2.1 on 2023-05-23 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GYMBookerapp', '0006_alter_membership_membership_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GYMBookerapp.membership'),
        ),
    ]
