# Generated by Django 4.2.1 on 2023-10-02 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GYMBookerapp', '0006_customer_is_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_currheight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_currweight',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
