# Generated by Django 4.2.1 on 2023-05-24 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GYMBookerapp', '0007_customer_customer_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_membership_joinedDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
