# Generated by Django 4.2.1 on 2023-05-19 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GYMBookerapp', '0007_class_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='customer',
        ),
        migrations.AddField(
            model_name='customer',
            name='joined_class',
            field=models.ManyToManyField(to='GYMBookerapp.class'),
        ),
    ]
