# Generated by Django 4.2.1 on 2023-10-02 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GYMBookerapp', '0007_customer_customer_count_customer_customer_currheight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_currheight',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_currweight',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_height',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_weight',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
