# Generated by Django 4.2.1 on 2023-05-24 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GYMBookerapp', '0008_customer_customer_membership_joineddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_membership_joinedDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
