# Generated by Django 4.2.1 on 2023-05-19 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GYMBookerapp', '0008_remove_class_customer_customer_joined_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='joined_class',
            field=models.ManyToManyField(null=True, to='GYMBookerapp.class'),
        ),
    ]
