# Generated by Django 4.2.1 on 2023-05-24 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GYMBookerapp', '0009_alter_customer_customer_membership_joineddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_membership_exipredDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
