# Generated by Django 4.2.1 on 2023-10-02 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GYMBookerapp', '0009_customer_customer_startbmi'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_bmidiff',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
