# Generated by Django 4.2.1 on 2023-05-25 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GYMBookerapp', '0010_customer_customer_membership_exipreddate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Days',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sunday', models.CharField(blank=True, max_length=9, null=True)),
                ('Monday', models.CharField(blank=True, max_length=9, null=True)),
                ('Tuesday', models.CharField(blank=True, max_length=9, null=True)),
                ('Wednesday', models.CharField(blank=True, max_length=9, null=True)),
                ('Thursday', models.CharField(blank=True, max_length=9, null=True)),
                ('Friday', models.CharField(blank=True, max_length=9, null=True)),
                ('Saturday', models.CharField(blank=True, max_length=9, null=True)),
            ],
        ),
    ]
