# Generated by Django 4.2.1 on 2023-05-25 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GYMBookerapp', '0011_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='class_day',
            field=models.ManyToManyField(blank=True, to='GYMBookerapp.days'),
        ),
    ]
