# Generated by Django 4.2.1 on 2023-05-25 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GYMBookerapp', '0012_class_class_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='days',
            name='Friday',
        ),
        migrations.RemoveField(
            model_name='days',
            name='Monday',
        ),
        migrations.RemoveField(
            model_name='days',
            name='Saturday',
        ),
        migrations.RemoveField(
            model_name='days',
            name='Sunday',
        ),
        migrations.RemoveField(
            model_name='days',
            name='Thursday',
        ),
        migrations.RemoveField(
            model_name='days',
            name='Tuesday',
        ),
        migrations.RemoveField(
            model_name='days',
            name='Wednesday',
        ),
        migrations.AddField(
            model_name='days',
            name='day',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
