# Generated by Django 4.2.1 on 2023-05-25 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GYMBookerapp', '0013_remove_days_friday_remove_days_monday_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(blank=True, max_length=9, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Days',
        ),
        migrations.RemoveField(
            model_name='class',
            name='class_endDay',
        ),
        migrations.RemoveField(
            model_name='class',
            name='class_startDay',
        ),
        migrations.AlterField(
            model_name='class',
            name='class_day',
            field=models.ManyToManyField(blank=True, to='GYMBookerapp.day'),
        ),
    ]
