# Generated by Django 4.2.1 on 2023-05-25 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GYMBookerapp', '0014_day_delete_days_remove_class_class_endday_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='class_day',
        ),
        migrations.DeleteModel(
            name='Day',
        ),
    ]
