# Generated by Django 4.2.1 on 2023-05-25 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GYMBookerapp', '0015_remove_class_class_day_delete_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='Days',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(blank=True, max_length=9, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='class_day',
            field=models.ManyToManyField(blank=True, to='GYMBookerapp.days'),
        ),
    ]
